Repository filecoin-project/devgrants, pull requests merged in 2022-03, with the labels that each got.

#344 Open Grant Proposal: Browser Based Web Archiving Design and Standardization
  open-grants/open-proposal-browser-based-web-archiving.md
Labels: category:app-dev, category:devtools-libraries, category:technical-design, wave-10, Approved

#415 RFP Proposal: Chainlink x Filecoin: Use Filecoin for Ethereum zk-Rollup storage
  rfp-proposals/rfp-proposal-filecoin-rollup.md
Labels: Approved

#424 RFP Proposal: Fil+ Notary Leaderboard
  rfps/rfp-notary-dashboard.md
Labels: Approved

#386 Open Grant Proposal: Adapt IPFS to ML and Data Pipelines
  open-grant-proposals/open-grant-proposal-adapt-ipfs-to-ml-and-data-pipelines
Labels: category:app-dev, category:devtools-libraries, Approved, wave-12

#380 NEAR x Filecoin RFP: Pristorage
  rfp-proposals/Pristorage.md
Labels: category:app-dev, Approved, rfp-type:near-x-filecoin

#336 Img8 open proposal.
  open-grants/open-proposal-img8.md
Labels: category:core-dev, wave-10, Approved
