Repository filecoin-project/devgrants, pull requests merged in 2022-04, with the labels that each got.

#368 NEAR x Filecoin RFP: Valist on NEAR
  rfp-proposals/rfp-proposal-template.md
  rfp-proposals/rfp-valist-on-near.md
Labels: category:app-dev, Approved, rfp-type:near-x-filecoin

#339 Open Grant proposal: Offline Signature Commands of Owner Wallet
  open-grants/open-proposal-offline-signature.md
Labels: category:devtools-libraries, wave-10, Approved

#343 Open Grant Proposal: Multi-Sector Memory Pool Support for The Sealing
  open-grants/open-proposal-p1-mem-pool.md
Labels: category:core-dev, wave-10, Approved

#302 Open Grant Proposal: Phu Quoc Dog
  open-grants/open-proposal-phuquoc-dog.md
Labels: category:app-dev, wave 9, Approved

#297 Open Proposal for crypto docs on IPFS, Filecoin, and Ethereum
  open-grants/open-proposal-crypto-docs.md
Labels: category:app-dev, wave 9, Approved

#294 New Dev Grants Proposal - Blockchain Solution for AI using Filecoin
  open-grants/project-blockchain-solution-for-AI-using-filecoin.md
Labels: category:app-dev, wave 9, Approved

#281 Open Grant Proposal: KryptoSeoul Community Development
  open-grant-proposals/open-proposal-kryptoseoulcommunity.md
Labels: category:community, wave 9, Approved

#274 Open grant proposal: Enterprise preprocessor layer for IPFS client
  open-grant-proposals/enterprise-preprocessor-layer-for-IPFS-client.md
Labels: category:app-dev, wave 9, Approved

#265 Create open-proposal-decoupling-winningpost-and-windowpost-from-lotus-miner
  open-grant-proposals/open-proposal-Improve-stability-of-miner.md
Labels: category:core-dev, wave-8, Approved

#264 open-grant-proposals: Bidirectional FIL <=> WFIL Bridge to Ethereum
  open-grant-proposals/open-proposal-wrapped-filecoin.md
Labels: category:app-dev, wave-8, Approved

#263 Open Grant Proposal: Machine Learning labeled Dataset NFT storage and sharing via IPFS_Filecoin
  open-grant-proposals/open-proposal-Machine Learning labled Dataset NFT storage and sharing via IPFS_Filecoin.md
Labels: category:app-dev, wave-8, Approved

#260 Add open proposal for vArtisans
  open-grant-proposals/open-proposal-vartisans.md
Labels: category:app-dev, wave-8, Approved

#253 Open Grant Proposal for Optimized Nitro State Channel Protocol
  open-grant-proposals/open-proposal-optimized-payments.md
Labels: category:technical-design, wave-8

#245 AIRport with Votecube seed project: Phase 1 - Basic Functionality Prototype
  .history/open-grant-proposals/autonomous-interdependent-repositories_20210609111255.md
  .history/open-grant-proposals/autonomous-interdependent-repositories_20210615161753.md
  open-grant-proposals/autonomous-interdependent-repositories.md
  open-grant-proposals/presentations/AIR Presentation - Short.pptx
  open-grant-proposals/presentations/AIR Presentation.pptx
  open-grant-proposals/presentations/Autonomous Interdependent Repositories.docx
  open-grant-proposals/presentations/images/AIR-across-devices.jpg
  open-grant-proposals/presentations/images/AIRPort_Transaction_Log.odg
  open-grant-proposals/presentations/images/AIRPort_Transaction_Log.png
  open-grant-proposals/presentations/images/AIRport-in-Cordova.drawio
  open-grant-proposals/presentations/images/AIRport-in-Cordova.png
  open-grant-proposals/presentations/images/AIRport_diagram_1.odg
  open-grant-proposals/presentations/images/AIRport_diagram_1.png
  open-grant-proposals/presentations/images/AIRport_diagram_2.odg
  open-grant-proposals/presentations/images/AIRport_diagram_2.png
  open-grant-proposals/presentations/images/Figure01.webp
  open-grant-proposals/presentations/images/Figure02.png
  open-grant-proposals/presentations/images/repositories-across-databasases.jpg
  open-grant-proposals/presentations/images/schema-publishing.jpg
Labels: category:devtools-libraries, wave-8, Approved

#241 Filecoin+OpenRPC grant pt.2
  open-grant-proposals/open-proposal-open-rpc-part-2.md
Labels: category:devtools-libraries, wave 7, Approved
